jobs:
  event-handler:
    if: ${{ github.event_name != 'issues' || github.event.action != 'opened' }}
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install GitHub Event Processor
      run: 'dotnet tool install Azure.Sdk.Tools.GitHubEventProcessor --version 1.0.0-dev.20240311.2
        --add-source https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json
        --global

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Process Action Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json

        '
      shell: bash
  event-handler-with-azure:
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    name: Handle ${{ github.event_name }} ${{ github.event.action }} event with azure
      login
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Az CLI login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    - continue-on-error: true
      name: Run Azure CLI commands
      run: "LABEL_SERVICE_API_KEY=$(az keyvault secret show \\\n  --vault-name issue-labeler\
        \ \\\n  -n issue-labeler-func-key \\\n  -o tsv \\\n  --query value)\n\necho\
        \ \"::add-mask::$LABEL_SERVICE_API_KEY\"\necho \"LABEL_SERVICE_API_KEY=$LABEL_SERVICE_API_KEY\"\
        \ >> $GITHUB_ENV\n"
    - continue-on-error: true
      name: Install GitHub Event Processor
      run: 'dotnet tool install Azure.Sdk.Tools.GitHubEventProcessor --version 1.0.0-dev.20240311.2
        --add-source https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json
        --global

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL_SERVICE_API_KEY: ${{ env.LABEL_SERVICE_API_KEY }}
      name: Process Action Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json

        '
      shell: bash
name: GitHub Event Processor
on:
  repository_dispatch:
    types: trigger-ga___event-processor.yml
permissions: {}
