jobs:
  event-handler:
    name: Handle ${{ github.event.schedule }} ${{ github.event.action }} event
    permissions:
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install GitHub Event Processor
      run: 'dotnet tool install Azure.Sdk.Tools.GitHubEventProcessor --version 1.0.0-dev.20240311.2
        --add-source https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json
        --global

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '0 1 * * *'
      name: Close Stale Issues Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json CloseStaleIssues

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '0 5 * * FRI'
      name: Identify Stale PullRequests Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json IdentifyStalePullRequests

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '30 2,8,14,20 * * *'
      name: Close Stale PullRequests Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json CloseStalePullRequests

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '30 3,9,15,21 * * *'
      name: Identify Stale Issues Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json IdentifyStaleIssues

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '30 4,10,16,22 * * *'
      name: Close Addressed Issues Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json CloseAddressedIssues

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '30 5,11,17,23 * * *'
      name: Lock Closed Issues Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json LockClosedIssues

        '
      shell: bash
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.schedule == '0 18 * * 1,3,5'
      name: Enforce Max Life of Issues Scheduled Event
      run: 'cat > payload.json << ''EOF''

        ${{ toJson(github.event) }}

        EOF

        github-event-processor ${{ github.event_name }} payload.json EnforceMaxLifeOfIssues

        '
      shell: bash
name: GitHub Scheduled Event Processor
on:
  repository_dispatch:
    types: trigger-ga___scheduled-event-processor.yml
permissions: {}
